### ISSUE TITLE
Colonic diverticula / colonic diverticulosis  [HP:0002253]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#19]
Colonic diverticulosis refers to the disease state, while colonic diverticula are an anatomical abnormality.  Should these be separate concepts?

**Comment by iamkoehler** [comment]
@pnrobinson  please advise

**Comment by pnrobinson** [comment]
The HPO term colonic diverticulosis is inteded to refer to the presence of multiple colonic diverticula rather than to the disease state. Perhaps it is better to have colonic diverticula be the primary term name and to have colonic diverticulosis as a RELATED_SYNONYM, since I agree there is potential for confusion.

**Comment by iamkoehler** [comment]
@mirandajarnot please reopen if this does not help

**Comment by mirandajarnot** [comment]
Thanks for the clarification on your definition.  I will leave them together in Meta as the anatomical abnormality, and not the disease state.
