### ISSUE TITLE
Nephrotic Syndrome / Nephrosis  [HP:0000100]

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#20]
Nephrotic Syndrome is a broad concept that encompasses nephrosis as part of its constellation of symptoms.  Should these two terms be split into separate concepts?

**Comment by iamkoehler** [comment]
would like to get an opinion from @pnrobinson or @markengelstad first

**Comment by pnrobinson** [comment]
My understanding is that "nephrotic syndrome" and "nephrosis" are used as synonyms. See for instance this website: https://www.nlm.nih.gov/medlineplus/ency/article/000490.htm
PS: The term is thus a "bundled" term that is refering to a disease, but since this disease occurs as a component of so many other diseases and syndromes, it is listed in the HPO as a phenotypic feature. Therefore, it my be OK to link it to semantic terms that are refering to the disease entity (tricky!)

Could you send us a reference for the assertion that nephrosis is actually not a synonym of nephrotic syndrome? Then let us decide how to treat these concepts in the HPO!

**Comment by mirandajarnot** [comment]
I can leave them as synonyms under Nephrotic Syndrome.  I agree that they do seem to be synonymous.  My question arose because we have two separate concepts for Nephrotic Syndrome and for Nephrosis, based on existing source data in the Metathesaurus, and  I wanted to make sure of HPO's meaning before I decided how to edit the concept.  
Thanks!

**Comment by iamkoehler** [comment]
Thank you!
