### ISSUE TITLE
HP:0011815 Cephalocele and HP:0002084 Encephalocele

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#27]
These two concepts are very hard to distinguish based on their definitions.  Could you please clarify the difference between the two?  Thank you.

**Comment by markengelstad** [comment]
Just for reference of whomever modifies the definitions in HPO:

Cephaloceles are complex neural axis malformations which manifest as herniation of the meninges and often cerebral tissue through a defect in the fetal calvarium. The commonly used term encephalocele describes the condition in which there is herniation of brain as well as the meninges.

http://www.fetalsono.com/teachfiles/enceph.lasso

**Comment by mirandajarnot** [comment]
UMLS has both Cephalocele and Encephalocele in the same concept, which is why I asked about your definitions.  Based on the above definition, cephalocele can be the same thing as encephalocele -- herniation of meninges and brain.

**Comment by pnrobinson** [comment]
The term cephalocele is rarely used but it is a superclass rather than a synonym of encephalocele. See the following comments from http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4426337/. I have added these comments to the HPO term as a comment.

A cephalocele is a rare birth defect that is characterized by a sac-like mass protruding through a defective opening in the skull. The sac varies in size that typically consists of herniated meninges and brain tissue (meningoencephalocele or encephalocele) or fragments of disorganized neural tissue. Alternatively, the sac may contain only the meninges (cranial meningocele) or it may include part of the ventricle filled with CSF (encephalocystocele) covered by skin.

This is the HPO definition: A congenital defect in the skull, whereby there is a protrusion of part of the cranial contents through a congenital defect in the cranium, usually covered with skin or mucous membrane. The term encephalocele refers to a subclass of these lesions in which brain tissue protrudes through the defect.
