### ISSUE TITLE
HP:0001973  Idio[pathic vs. autoimmune thrombocytopenia

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#28]
HPO has Autoimmune and Idiopathic Thrombocytopenia in the same concept.  Should Autoimmune be narrower?  We have separate concepts for each of these in the Metathesaurus.

Thanks,
Miranda

**Comment by pnrobinson** [comment]
Actually, idiopathic thrombocytopenia is not a good concept for the HPO since it is not describing a specific phenotype, but rather a phenotype whose cause is unknown. Autoimmune thrombocytopenia is on the borderline between a specific phenotype and a disease, but it is I think valid to describe the finding of low platelets together with platelet autoantibodies. In principle, "Autoimmune thrombocytopenia" is seen with the disease "Idiopathic thrombocytopenic purpura", which I think is a valid RELATED_SYNONYM.
I have therefore removed the database xref (UMLS:C0920163 - idiopathic thrombocytopenia), and also the EXACT_SYNONYM of the same name. I have changed "Idiopathic thrombocytopenic purpura" to a RELATED_SYNONYM.
Please re-open if this does not work for you!
-Peter
