### ISSUE TITLE
Meta Concept #243679484  Anxiety Disease

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#3]
Does this HPO concept mean the same thing as Anxiety Disorders (#1001850)?  Or should it remain a separate concept?

CN# 243679484  Anxiety disease
    Concept Status needs Review
ATOMS
               N []  Anxiety disease [HPO2015_04_20/ET/HP:0000739]

**Comment by pnrobinson** [comment]
HP:0000739 (Anxiety; Definition=Feeling or dread, apprehension, and impending disaster) is a phenotypic feature. On the other hand,  according to NIMH, "Anxiety disorders involve more than temporary worry or fear. For a person with an anxiety disorder, the anxiety does not go away and can get worse over time. These feelings can interfere with daily activities such as job performance, school work, and relationships"; the latter is a disease since it is describing a set of abnormalities, a disease course, and could in principle also describe an etiology. I notice that the HPO has "anxiety disorder" as a synonym, but actually this should be RELATED_SYNONYM, since it is not an exact match (I will put this on the main HPO tracker).
So: I think it should remain a separate concept.

**Comment by mirandajarnot** [comment]
Could you please define “anxiety disease”, “anxiety disorder”, and “anxiety” from the HPO point of view?

Thanks,
Miranda

**Comment by pnrobinson** [comment]
"Anxiety" is a phenotpyic abnormality or trait. "Anxiety disease" is poorly defined for me but it can be a disease entity that is characterized by anxiety and potentially other symptoms, it has a possibly unknown cause, and it has a natural history (typical course) as well as an expected response to certain treatments. Is that OK?

**Comment by mellybelly** [comment]
I agree with Peter, we need an atomic anxiety phenotype in HPO, and keep a disease concept for Anxiety disease /  Anxiety disorder. Some of these diseases will have only one phenotype associated "anxiety phenotype" but others would have many others. 

It is hard when there is only one known phenotype for a given disease, but I still think it behooves us to keep these concepts separate.

**Comment by mirandajarnot** [comment]
Thanks for your consideration.  We want to make sure that we are representing HPO concepts correctly, and your feedback and thoughtfulness are much appreciated.

**Comment by iamkoehler** [comment]
If I understood correctly, this ticket can be closed. Feel free to reopen if I am wrong.

**Comment by mirandajarnot** [comment]
Yes, fine to close… thanks!
