### ISSUE TITLE
Microcephaly

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#30]
The concepts Microcephaly (HP:0000252) and Decreased head circumference (HP:0040195) have very similar strings between them.  Do all the synonyms in Microcephaly refer specifically to the syndrome, and not to the finding of small head size?

A similar situation exists with Macrocephaly (HP:0000256) and Increased head circumference (HP:0040194).

Thanks,
Miranda Jarnot

**Comment by markengelstad** [comment]
i think the way microcephaly is modeled now, it is representing both the
syndrome and the finding of a skull that is very small -- so you are seeing
a lot of synonyms in there.

That's because, right now, microcephaly is the only class for representing
an overall small skull (not just in circumference).

we should add another term 'Decreased size of skull' to capture some of the
more non-specific terms that are currently synonyms of microcephaly, like
'small skull'.

and microcephaly should be reserved for certain type of small skull defined
by particular head circumference values

**Comment by iamkoehler** [comment]
please have a look at https://github.com/obophenotype/human-phenotype-ontology/issues/497 for further information on the current solution for this part of HPO.

may be true that some synonyms should be moved. will look at this later

**Comment by mirandajarnot** [comment]
Thank you, Seb, this is very helpful.  It’s good to see how you (HPO) view things and how they are considered, and makes it easier for editing HPO in the UMLS.

Miranda

**Comment by pnrobinson** [comment]
This issue seems to be closed? Note that the HPO class microcephaly is refering to the phenotypic finding of a small skull, not the disease known as microcephaly (this disease typically also is characterized by intellectual disability and perhaps other abnormalities).

**Comment by mirandajarnot** [comment]
Thanks Peter – this is exactly what I needed to know to make sure we have this edited correctly in the Metathesaurus.

Thanks,
Miranda Jarnot
