### ISSUE TITLE
Hyperalaninemia

### ISSUE THREAD

**Issue by mirandajarnot** [monarch-initiative/HPO-UMLS-Integration#6]
HPO #0003348 appears to combine the concepts of the finding of increased serum/blood alanine with the disorder, hyperalaninemia.  These are separate concepts in UMLS.  Could you please look at these and explain why they are synonymous in HPO?  Thank you.

**Comment by pnrobinson** [comment]
An HPO term only refers to the phenotypic feature and never to the disease. I disagree that hyperalaninemia must refer to the disease. For instance, here
http://www.ncbi.nlm.nih.gov/pubmed/817914
The disease is "pyruvate carboxylase deficiency of the liver", and hyperalaninemia is one of the phenotypic features.
There are lots of cases analogous to this. I think that it is good to keep all of the synonyms with the HPO term because people search for them. But we have to make sure that users know the difference between phenotypic features and disease entities if that is important for their use case.
I am not sure if this addresses your comment though, could you let me know?

**Comment by mirandajarnot** [comment]
In this and similar cases, we would prefer to keep the synonyms separate, as we have separate existing concepts in the Metathesaurus.  We do not feel as though it would be a correct representation of our other sources to merge them into one.

We can either:

1)      split the HPO synonyms, so that each synonym goes into a separate Metathesaurus concept.  In this case, there are separate concepts for Hyperalanimemia, Increased serum alanine, and Increased blood alanine; or

2)      Keep the three HPO synonyms together and respect HPO’s synonymy.

Please let me know which option you would prefer for these HPO synonyms, and as a precedent for similar cases in the future.

**Comment by pnrobinson** [comment]
Sorry for the late reply, I have been partially on vacation recently. Medically, there is not any difference I know of between increased serum and increased blood alanine, this is a question perhaps of how something was measured (or recorded). In this case, the HPO would conflate the two synonyms, because the HPO does not care much about measure technologies, just about the "true" phenotypes. I would agree though that it is important to distinguish between the phenotype (that you are calling increased blood/serum alanine) and the disease (that you are calling hyperalaninemia). Again I am not sure that the medical community would necessarily think of a disease entity and not a phenotype if they heard "hyperalaninemia". I am not sure the best way to proceed but maybe we should try to disambbiguate this in the HPO definition?

**Comment by mirandajarnot** [comment]
No problem.  We are all in various stages of vacation here as well.

I think it would be a good idea in this case to disambiguate phenotype and disease in the HPO definition.  That way we can maintain our source representation in the Metathesaurus, without disrespecting HPO.

As for the serum/blood question, though they are medically indistinct, separating the two concepts is a convention agreed upon by UMLS clinical analysts some time ago.

Thanks for your input… it is very helpful for our editors.

**Comment by iamkoehler** [comment]
Can I close this issue then?

**Comment by mirandajarnot** [comment]
Has the definition been disambiguated as discussed above? 
"maybe we should try to disambbiguate this in the HPO definition?"

**Comment by iamkoehler** [comment]
I added to the comment annotation the sentence "This class referring to the clinical feature Hyperalaninemia and not to the disease entry." Does that help?

**Comment by mirandajarnot** [comment]
Yes, thank you!

**Comment by iamkoehler** [comment]
Awesome! Thank you
